// PaOh basic layout, checked against /usr/share/X11/xkb/symbols/pao
// on 2026-10-07. These are direct key outputs, not an IME reorder model.
export interface KeyHint { readonly code: string; readonly label: string; readonly shift: boolean; readonly text: string }

export const paoKeyLegends: Record<string, { shifted: string; unshifted: string }> = {
  Backquote: { shifted: "ဎ", unshifted: "ၐ" },
  Digit1: { shifted: "ဍ", unshifted: "၁" },
  Digit2: { shifted: "ၒ", unshifted: "၂" },
  Digit3: { shifted: "ဋ", unshifted: "၃" },
  Digit4: { shifted: "ၓ", unshifted: "၄" },
  Digit5: { shifted: "ၔ", unshifted: "၅" },
  Digit6: { shifted: "ၕ", unshifted: "၆" },
  Digit7: { shifted: "ရ", unshifted: "၇" },
  Digit8: { shifted: "*", unshifted: "၈" },
  Digit9: { shifted: "(", unshifted: "၉" },
  Digit0: { shifted: ")", unshifted: "၀" },
  Minus: { shifted: "_", unshifted: "-" },
  Equal: { shifted: "+", unshifted: "=" },
  KeyQ: { shifted: "ဈ", unshifted: "ဆ" },
  KeyW: { shifted: "ဝ", unshifted: "တ" },
  KeyE: { shifted: "ဣ", unshifted: "န" },
  KeyR: { shifted: "၎", unshifted: "မ" },
  KeyT: { shifted: "ဤ", unshifted: "အ" },
  KeyY: { shifted: "၌", unshifted: "ပ" },
  KeyU: { shifted: "ဥ", unshifted: "က" },
  KeyI: { shifted: "၍", unshifted: "င" },
  KeyO: { shifted: "ဿ", unshifted: "သ" },
  KeyP: { shifted: "ဏ", unshifted: "စ" },
  BracketLeft: { shifted: "ဧ", unshifted: "ဟ" },
  BracketRight: { shifted: "ဪ", unshifted: "ဩ" },
  Backslash: { shifted: "ၑ", unshifted: "၏" },
  KeyA: { shifted: "ဗ", unshifted: "ေ" },
  KeyS: { shifted: "ှ", unshifted: "ျ" },
  KeyD: { shifted: "ီ", unshifted: "ိ" },
  KeyF: { shifted: "္", unshifted: "်" },
  KeyG: { shifted: "ွ", unshifted: "ါ" },
  KeyH: { shifted: "ံ", unshifted: "့" },
  KeyJ: { shifted: "ဲ", unshifted: "ြ" },
  KeyK: { shifted: "ဒ", unshifted: "ု" },
  KeyL: { shifted: "ဓ", unshifted: "ူ" },
  Semicolon: { shifted: "ဂ", unshifted: "း" },
  Quote: { shifted: "\"", unshifted: "'" },
  KeyZ: { shifted: "ဇ", unshifted: "ဖ" },
  KeyX: { shifted: "ဌ", unshifted: "ထ" },
  KeyC: { shifted: "ဃ", unshifted: "ခ" },
  KeyV: { shifted: "ဠ", unshifted: "လ" },
  KeyB: { shifted: "ယ", unshifted: "ဘ" },
  KeyN: { shifted: "ဉ", unshifted: "ည" },
  KeyM: { shifted: "ဦ", unshifted: "ာ" },
  Comma: { shifted: "၊", unshifted: "ꩻ" },
  Period: { shifted: "။", unshifted: "ႏ" },
  Slash: { shifted: "?", unshifted: "/" },
};

