-- Shared lesson content. Administrators are provisioned via trusted Auth app_metadata only.
create table if not exists public.lesson_catalog (
  id integer generated by default as identity primary key,
  title text not null check (char_length(title) between 1 and 80),
  description text not null check (char_length(description) between 1 and 240),
  difficulty text not null check (difficulty in ('Beginner', 'Intermediate', 'Advanced')),
  category text not null check (category in ('Beginner', 'Intermediate', 'Advanced', 'Programming')),
  duration_minutes integer not null check (duration_minutes between 1 and 180),
  content text not null check (char_length(content) between 10 and 3000),
  status text not null default 'Draft' check (status in ('Published', 'Draft')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.set_lesson_catalog_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := pg_catalog.now();
  return new;
end;
$$;
revoke all on function public.set_lesson_catalog_updated_at() from public, anon, authenticated;

drop trigger if exists lesson_catalog_updated_at on public.lesson_catalog;
create trigger lesson_catalog_updated_at before update on public.lesson_catalog
  for each row execute function public.set_lesson_catalog_updated_at();

insert into public.lesson_catalog (id, title, description, difficulty, category, duration_minutes, content, status) values
  (1, 'Home Row Keys', 'Master ASDF and JKL; — the foundation of touch typing.', 'Beginner', 'Beginner', 10, 'asdf jkl; asdf jkl; sad lad fall ask flask', 'Published'),
  (2, 'Top Row Keys', 'Expand to QWERTY and YUIOP with proper finger placement.', 'Beginner', 'Beginner', 12, 'qwer tyui op qwer tyui op type the top row with steady rhythm', 'Published'),
  (3, 'Bottom Row Keys', 'Complete the full keyboard with ZXCVB and NM,./', 'Beginner', 'Beginner', 15, 'zxcv bnm zxcv bnm practice the bottom row with relaxed hands', 'Published'),
  (4, 'Common Words', 'Practice the 100 most common English words for fluency.', 'Intermediate', 'Intermediate', 20, 'the quick brown fox jumps over the lazy dog while we practice common words', 'Published'),
  (5, 'Numbers & Symbols', 'Tackle number row and shift-key symbols efficiently.', 'Intermediate', 'Intermediate', 18, '12345 67890 ! @ # $ % use the number row with careful accuracy', 'Published'),
  (6, 'Speed Drills', 'Push your WPM ceiling with intensive speed exercises.', 'Advanced', 'Advanced', 25, 'steady rhythm and accurate movement build speed through focused daily practice', 'Published'),
  (7, 'JavaScript Syntax', 'Type common JS patterns, arrow functions, and destructuring.', 'Advanced', 'Programming', 30, 'const greet = (name) => `Hello, ${name}!`; console.log(greet(''world''));', 'Published'),
  (8, 'Python Patterns', 'Practice Python indentation, list comprehensions, and f-strings.', 'Advanced', 'Programming', 28, 'def greet(name):
    return f''Hello, {name}!''

print(greet(''world''))', 'Published')
on conflict (id) do nothing;

select pg_catalog.setval(
  pg_catalog.pg_get_serial_sequence('public.lesson_catalog', 'id'),
  greatest(coalesce((select max(id) from public.lesson_catalog), 1), 1),
  true
);

do $$
begin
  if not exists (
    select 1 from pg_catalog.pg_constraint
    where conname = 'completed_lessons_catalog_lesson_fk'
      and conrelid = 'public.completed_lessons'::regclass
  ) then
    alter table public.completed_lessons
      add constraint completed_lessons_catalog_lesson_fk
      foreign key (lesson_id) references public.lesson_catalog (id)
      on delete restrict not valid;
  end if;
end;
$$;

alter table public.lesson_catalog enable row level security;
revoke all on public.lesson_catalog from anon, authenticated;
grant select on public.lesson_catalog to anon, authenticated;
grant insert, update, delete on public.lesson_catalog to authenticated;

drop policy if exists "Readers see published lessons" on public.lesson_catalog;
create policy "Readers see published lessons"
  on public.lesson_catalog for select to anon, authenticated
  using (status = 'Published');

drop policy if exists "Admins see all lessons" on public.lesson_catalog;
create policy "Admins see all lessons"
  on public.lesson_catalog for select to authenticated
  using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "Admins insert lessons" on public.lesson_catalog;
create policy "Admins insert lessons"
  on public.lesson_catalog for insert to authenticated
  with check ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "Admins update lessons" on public.lesson_catalog;
create policy "Admins update lessons"
  on public.lesson_catalog for update to authenticated
  using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
  with check ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "Admins delete lessons" on public.lesson_catalog;
create policy "Admins delete lessons"
  on public.lesson_catalog for delete to authenticated
  using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create or replace function public.restore_default_lesson_catalog()
returns void
language plpgsql
set search_path = ''
as $$
begin
  if (select auth.jwt() -> 'app_metadata' ->> 'role') is distinct from 'admin' then
    raise exception 'Administrator access required' using errcode = '42501';
  end if;

  update public.lesson_catalog set status = 'Draft' where id > 8;
  insert into public.lesson_catalog (id, title, description, difficulty, category, duration_minutes, content, status) values
    (1, 'Home Row Keys', 'Master ASDF and JKL; — the foundation of touch typing.', 'Beginner', 'Beginner', 10, 'asdf jkl; asdf jkl; sad lad fall ask flask', 'Published'),
    (2, 'Top Row Keys', 'Expand to QWERTY and YUIOP with proper finger placement.', 'Beginner', 'Beginner', 12, 'qwer tyui op qwer tyui op type the top row with steady rhythm', 'Published'),
    (3, 'Bottom Row Keys', 'Complete the full keyboard with ZXCVB and NM,./', 'Beginner', 'Beginner', 15, 'zxcv bnm zxcv bnm practice the bottom row with relaxed hands', 'Published'),
    (4, 'Common Words', 'Practice the 100 most common English words for fluency.', 'Intermediate', 'Intermediate', 20, 'the quick brown fox jumps over the lazy dog while we practice common words', 'Published'),
    (5, 'Numbers & Symbols', 'Tackle number row and shift-key symbols efficiently.', 'Intermediate', 'Intermediate', 18, '12345 67890 ! @ # $ % use the number row with careful accuracy', 'Published'),
    (6, 'Speed Drills', 'Push your WPM ceiling with intensive speed exercises.', 'Advanced', 'Advanced', 25, 'steady rhythm and accurate movement build speed through focused daily practice', 'Published'),
    (7, 'JavaScript Syntax', 'Type common JS patterns, arrow functions, and destructuring.', 'Advanced', 'Programming', 30, 'const greet = (name) => `Hello, ${name}!`; console.log(greet(''world''));', 'Published'),
    (8, 'Python Patterns', 'Practice Python indentation, list comprehensions, and f-strings.', 'Advanced', 'Programming', 28, 'def greet(name):
    return f''Hello, {name}!''

print(greet(''world''))', 'Published')
  on conflict (id) do update set
    title = excluded.title,
    description = excluded.description,
    difficulty = excluded.difficulty,
    category = excluded.category,
    duration_minutes = excluded.duration_minutes,
    content = excluded.content,
    status = excluded.status;
end;
$$;
revoke all on function public.restore_default_lesson_catalog() from public, anon;
grant execute on function public.restore_default_lesson_catalog() to authenticated;

do $$
begin
  if exists (select 1 from pg_catalog.pg_publication where pubname = 'supabase_realtime')
    and not exists (
      select 1 from pg_catalog.pg_publication_tables
      where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'lesson_catalog'
    ) then
    alter publication supabase_realtime add table public.lesson_catalog;
  end if;
end;
$$;
