import { freezeProfileValue } from "../aggregation";
/** Composition contracts, never scoring/timer policy. Baseline Slice 6 remains intact. */
export const COMPOSITION = freezeProfileValue({
  version: "composition-v1",
  generatorVersion: "adaptive-composition-v3",
  contentVersion: "english-context-v3",
  cycle: 32,
  maxVariants: 64,
  maxOrdinal: 1_000_000_000,
  attempts: 16,
  maxChunks: 48,
  tolerance: { min: 0.9, max: 1.1 },
  levels: [
    {
      length: 160,
      shares: [0.22, 0.38, 0.4],
      mixedMin: 0.35,
      mixedMax: 0.5,
      maxDensity: 0.4,
      contexts: 3,
      tokenContexts: 3,
      ordinary: 3,
      identicalShare: 0.25,
      identicalRun: 2,
      grapheme: [6, 7, 5],
      counterpart: [5, 5, 4],
      bigram: [4, 5, 5],
      token: [2, 2, 2],
    },
    {
      length: 220,
      shares: [0.11, 0.3, 0.59],
      mixedMin: 0.5,
      mixedMax: 0.68,
      maxDensity: 0.25,
      contexts: 4,
      tokenContexts: 4,
      ordinary: 6,
      identicalShare: 0.2,
      identicalRun: 1,
      grapheme: [4, 6, 5],
      counterpart: [3, 5, 4],
      bigram: [3, 5, 4],
      token: [1, 2, 2],
    },
    {
      length: 300,
      shares: [0.06, 0.2, 0.74],
      mixedMin: 0.65,
      mixedMax: 0.85,
      maxDensity: 0.16,
      contexts: 5,
      tokenContexts: 4,
      ordinary: 12,
      identicalShare: 0.15,
      identicalRun: 1,
      grapheme: [3, 5, 4],
      counterpart: [3, 4, 3],
      bigram: [2, 4, 4],
      token: [1, 2, 1],
    },
  ],
  assessment: {
    length: 300,
    shares: [0.06, 0.25, 0.69],
    mixedMin: 0.6,
    mixedMax: 0.85,
    maxDensity: 0.1,
    contexts: 5,
    tokenContexts: 2,
    ordinary: 15,
    identicalShare: 0.12,
    identicalRun: 1,
    grapheme: [0, 5, 5],
    counterpart: [0, 4, 4],
    bigram: [0, 3, 3],
    token: [0, 1, 1],
  },
});
/** Explicit alternative path: no fuzzy mixing of ordinary and controlled evidence. */
export const ASSESSMENT = freezeProfileValue({
  waitingSessions: 5,
  ordinaryAttempts: 40,
  ordinaryMs: 1000,
  window: 5,
  sessions: { grapheme: 4, substitution: 4, bigram: 5, token: 3 },
  total: { grapheme: 40, substitution: 40, bigram: 30, token: 6 },
  perSession: { grapheme: 10, substitution: 10, bigram: 6, token: 2 },
  accuracy: 99.5,
  minActiveMs: 1000,
  minAttempts: 100,
});
