import { ENGLISH_CONTENT, prepareContentBank } from "../exercises/content";
import { COMPOSITION } from "./constants";
/** Original familiar contexts, with short phrases for warm-ups and connected clauses. */
const CONTEXTS = [
  "calm waves move by",
  "blue skies shine above us",
  "small dogs play by a lake",
  "high hills glow below a blue sky",
  "small foxes jump by a lake",
  "clouds move above high hills",
  "cool winds move along a wide sea",
  "books lie beside a pen",
  "open a book and find a new idea",
  "home feels calm on a cool day",
  "leaves move as a cool wind flows by",
  "dogs walk by a small lake",
  "we see a wide sea",
  "we see a small lake",
  "we see a high hill",
  "a cool wind moves by",
  "we look up and see a blue sky",
  "we see a small fox jump",
  "a cloud moves above us",
  "we see a wave on a wide sea",
  "we know a safe way home",
  "we can walk a long way",
  "we smile as a small dog plays",
  "we have a calm place by a lake",
  "we see a book on a desk",
  "we keep a calm pace",
  "we can open a book",
  "we look back and see a small hill",
  "we see a calm lake below a high hill",
  "a blue sky is above a wide sea",
  "a small dog plays by a lake",
  "we see a book and a pen",

  "red birds rest",
  "read the road map",
  "the river runs near home",
  "warm rain fills the garden",
  "bring the brown bag home",
  "three thin threads",
  "think through the next step",
  "the path leads through the trees",
  "look through each page with care",
  "we walk through the gate together",
  "read through the notes before we begin",
  "the light shines through the window",
  "we move through the room at a calm pace",
  "follow the road through the garden",
  "the warm light falls on the desk",
  "a small boat moves along the water",
  "we open a book and read each page",
  "each day we take a short walk",
  "a blue sky brings a quiet day",
  "the soft wind moves the tall grass",
  "we take care of each other",
  "a clear plan helps the team work",
  "the next step is small and steady",
  "our friends meet by the gate",
  "we write a note and turn the page",
  "the white cloud moves over the hill",
  "a bright light fills the quiet room",
  "read each line before you begin",
  "keep a steady pace as you move along",
  "the garden has a small path and a gate",
  "we see a bird and hear a soft song",
  "the old book has a map of the town",
  "we sit near the open window and read",
  "a light wind brings the sound of rain",
  "the road bends near a small green field",
  "write one clear line then take a rest",
  "a warm cup sits beside the book",
  "the team can find a clear way ahead",
  "we can move from one small step to the next",
  "a short walk helps us feel at ease",
  "the day is calm and the path is clear",
  "we read the words and keep a steady rhythm",
  "take a deep breath and let your hands rest",
  "the leaves move as the wind flows past",
  "we follow the path and watch the light",
  "a quiet place gives us time to think",
  "the room is warm and the light is soft",
  "we take our time and check each word",
  "a small bird flies over the garden wall",
  "the next page has a clear line of text",
  "we look at the map and choose a path",
  "our hands rest while we read the next line",
  // Original e/i-free surroundings: the v2 bank had zero target-free phrases
  // for e→i, so mixed/controlled sections could never reach their length.
  "soft clouds pass",
  "warm sun glows",
  "dogs run across soft grass",
  "small boats bob on choppy surf",
  "oak logs stand by tall barns",
  "young ducks splash along shallow pools",
  "brown owls swoop past old walls",
  "snow falls upon rocky crags",
  "gold lamps glow on broad paths",
  "calm swans float toward sunny banks",
  "strong arms hold long planks",
  "fox cubs jump across smooth rocks",
  "slow drops fall from low clouds",
  "bold chalk marks show sharp turns",
  "our cat curls up on soft wool",
  // Article-free a-free filler avoids exhausting controlled-a repetition
  // headroom on "the" in the otherwise small v2 target-free pool.
  "birds sing softly",
  "moonlight fills this room",
  "cool winds ripple over ponds",
  "fresh fruit rests on this desk",
  "quiet footsteps echo through rooms",
  "bright yellow blooms grow outdoors",
  "little silver fish swim below",
  "soft snow drifts over hills",
];
const accuracy = [
  ...ENGLISH_CONTENT.accuracy.map((c) => c.text),
  ...CONTEXTS.slice(12, 32),
];
const speed = [
  ...ENGLISH_CONTENT.speed.map((c) => c.text),
  ...CONTEXTS.slice(32),
];
export const PROGRESSION_CONTENT = prepareContentBank(
  COMPOSITION.contentVersion,
  ENGLISH_CONTENT.words.map((c) => c.text),
  {
    accuracy,
    speed,
    general: [...ENGLISH_CONTENT.general.map((c) => c.text), ...CONTEXTS],
  },
);
